<!DOCTYPE html>

<html lang="es">
   <head>
      <?php 
            $titulo = "Menciones seguidos";
            require "appweb/mod/header.php"; 
            require "appweb/inc/funmenciones.php";
      ?>
   </head>

   <body class="animsition">
      
      <!-- Modal para añadir registros-->
      <?php require "appweb/mod/reglaModal.php"; ?>
      <div class="page-wrapper">
         
         <!-- Menu-->
         <?php require "appweb/mod/menu.php"; ?>

         <!-- Contenido principal-->
         <div class="page-container">

            <div class="section__content section__content--p30">
               <div class="container-fluid">
                  <div class="row">
                     <div class="col-md-12">
                        
                        <!-- Titulo -->
                        <?php require "appweb/mod/titulo.php"; ?>
                        
                        <div class="table-data__tool">
                           <div class="table-responsive table-responsive-data2">
                           
                              <!-- Tabla de resultados -->
                              <table class="table table-data2">
                                 
                                 <!-- Cabecera de la tabla -->
                                 <thead>
                                    <tr>
                           <!--1-->    <th></th>                                 
                                       <th>
                           <!--2-->       Nombre de usuario  
                                       </th>
                                       <th>
                           <!--3-->       Seguidores
                                       </th>
                                       <th>
                           <!--4-->       Cantidad
                                       </th>
                           <!--6-->    <th></th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                    <?php
                                       
                                       #Eliminar hashtag del seguimiento
                                       if(isset($_POST['eliminarseguimiento'])){
                                          // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
                                          $idUsuario = $_POST['idUsuario'];
                                          $nombreUsuario = $_POST['nombreUsuario'];
                                          // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
                                          $ch = curl_init();

                                          curl_setopt($ch, CURLOPT_URL, 'https://api.twitter.com/2/tweets/search/stream/rules');
                                          curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                          curl_setopt($ch, CURLOPT_POST, 1);
                                          curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"delete\": {\"values\": [\"from:".$nombreUsuario."\"]}}");

                                          $headers = array();
                                          $headers[] = 'Content-Type: application/json';
                                          $headers[] = 'Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAPbENwEAAAAAo90kIhuPyTepkpQ5IN5OrhtlOtA%3DYedpthaxickJlKMh1LiZK3zGGMsCKfmbAnsoVnaBCc3yLSt9f4';
                                          curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

                                          $result = curl_exec($ch);
                                          if (curl_errno($ch)) {
                                             echo 'Error:' . curl_error($ch);
                                          }
                                          curl_close($ch);
                                          $post = "UPDATE `usuarios` SET `post`=0 WHERE `id` = $idUsuario";
                                          $result = mysqli_query($db,$post);
                                       }

                              
                                       #Sentencia de datos
                                       $query = "SELECT * FROM `menciones` where `eliminado`='0' and `post`=1 order by countotal";
                                       $result = mysqli_query($db,$query);

                                       if($result){
                                          while($row = mysqli_fetch_array($result)){
                                             $nickname = $row['nickname'];
                                             $followers = $row['followers'];
                                             $seleccionado = $row['seleccionado'];

                                 
                                             $cantidad = $row['countotal']; #Cantidad por defecto
                                             if ($filtro == 1 ){ $cantidad = $row['count']; }
                                             if ($filtro == 2 ){ $cantidad = $row['countres']; }
                                             if ($filtro == 3 ){ $cantidad = $row['countsemana']; }
                                             
                                             if ($cantidad > 1){?>
                                             
                                             <tr class='tr-shadow'>
                                                <td>
                                    <!--2-->       <a href='https://twitter.com/<?php echo $nickname?>' target="_blank" class='block-email'>@<?php echo $nickname?></a>
                                                </td>
                                    <!--3-->    <td><?php echo $followers ?></td>
                                                <td>
                                    <!--4-->       <?php echo $cantidad ?>
                                                </td>
                                                <form method="post" action="seguimientop.php">
                                                <td>
                                                   <div class='table-data-feature'>
                                                         <input type="hidden" name="idUsuario" value="<?php echo $row['id'] ?>">
                                                         <input type="hidden" name="nombreUsuario" value="<?php echo $row['nickname'] ?>">
                                                         <button type="submit" name='eliminarseguimiento'class="item" style="display: block;height: 30px;width: 30px;position: relative;-webkit-border-radius: 100%;-moz-border-radius: 100%;border-radius: 100%;margin-right: 5px;" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="zmdi zmdi-delete"></i></button>
                                                   </div>
                                                </td>
                                                </form>
                                    <!--6-->    <td></td>
                                             </tr>
                                             <tr class='spacer'></tr>   
                                       <?php }}}?>
                                 </tbody>
                              </table>
                           </div>
                        </div>
                     </div>
                     <!-- Pie de pagina-->
                     <?php require "appweb/mod/footer.php"; ?>
                  </div>
               </div>
            </div>
         </div>
      </div>  
      
      <!-- Jquery JS-->
      <?php require "appweb/inc/jquerys.php"; ?>  

   </body>
</html>
