<?php

#Filtro para agregar nueva reglla
if(isset($_POST['agregarnuevaregla'])){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $tiporegla = $_POST['selectregla'];
    $variable = $_POST['varregla'];

    if($tiporegla == 1) {
        $regla = "{ \"add\": [ {\"value\": \"#".$variable." lang:es\", \"tag\": \"".$variable." hashtag\"}] }";
        $query = "INSERT INTO `hashtags`(`hashtag`, `post`) VALUES ('$variable', 1)";
        $result = mysqli_query($db,$query);
    }

    if($tiporegla == 2) {
        $regla = "{ \"add\": [ {\"value\": \"".$variable." lang:es\", \"tag\": \"".$variable."\"}] }";
    }

    if($tiporegla == 3) {
        $regla = "{ \"add\": [ {\"value\": \"from:".$variable."\", \"tag\": \"".$variable." user\"}] }";
        $query = "INSERT INTO `usuarios`(`nickname`, `post`) VALUES ('$variable', 1)";
        $result = mysqli_query($db,$query);
    }

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.twitter.com/2/tweets/search/stream/rules');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $regla);

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAPbENwEAAAAAo90kIhuPyTepkpQ5IN5OrhtlOtA%3DYedpthaxickJlKMh1LiZK3zGGMsCKfmbAnsoVnaBCc3yLSt9f4';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
       echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
 ?>
 <div class="sufee-alert alert with-close alert-success alert-dismissible fade show">
          <span class="badge badge-pill badge-success">Añadido</span>
         Se añadio la monitorización exitosamente.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>

 <?php }

?>