<?php

/** 
 *  Funciones para los usuarios
 * 
 * @package  UAL Transfiere
 * @author   Alberto Fuentes <aff012@inlumine.ual.es>
 * @link     https://twitter.com/21albertoff
 *
 */

   $filtro = 0;

    #Filtro para seleccionar
    if(isset($_POST['seleccionar'])){
       $idUsuario = $_POST['idUsuario'];
       $seleccionar = "UPDATE `menciones` SET `seleccionado`='1' WHERE `id` = $idUsuario";
       $result = mysqli_query($db,$seleccionar);
   }

   #Filtro para agregar nueva reglla
   if(isset($_POST['nuevaregla'])){
      // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
      $ch = curl_init();
      $nombreUsuario = $_POST['nombreUsuario'];
      $idUsuario = $_POST['idUsuario'];
      $regla = "{ \"add\": [ {\"value\": \"from:".$nombreUsuario."\", \"tag\": \"".$nombreUsuario." user\"}] }";

      curl_setopt($ch, CURLOPT_URL, 'https://api.twitter.com/2/tweets/search/stream/rules');
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_POST, 1);
      curl_setopt($ch, CURLOPT_POSTFIELDS, $regla);

      $headers = array();
      $headers[] = 'Content-Type: application/json';
      $headers[] = 'Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAPbENwEAAAAAo90kIhuPyTepkpQ5IN5OrhtlOtA%3DYedpthaxickJlKMh1LiZK3zGGMsCKfmbAnsoVnaBCc3yLSt9f4';
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

      $result = curl_exec($ch);
      if (curl_errno($ch)) {
         echo 'Error:' . curl_error($ch);
      }
      curl_close($ch);
      $post = "UPDATE `menciones` SET `post`=1 WHERE `id` = $idUsuario";
      $result = mysqli_query($db,$post);

   }
   
   #Filtro para deseleccionar
   if(isset($_POST['deseleccionar'])){
       $idUsuario = $_POST['idUsuario'];
       $deseleccionar = "UPDATE `menciones` SET `seleccionado`='0' WHERE `id` = $idUsuario";
       $result = mysqli_query($db,$deseleccionar);
   }

    #Filtro para recopilar datos
    if(isset($_POST['recopilar'])){
        $recopilar = "UPDATE `menciones` SET `countsemana`=`countres`";
        $result = mysqli_query($db,$recopilar);
        $recopilar2 = "UPDATE `menciones` SET `countres`=`count`";
        $result = mysqli_query($db,$recopilar2);
        $recopilar3 = "UPDATE `menciones` SET `count`=1";
        $result = mysqli_query($db,$recopilar3);
    }

    #Filtro para recopilar datos
    if(isset($_POST['deseleccionarTodos'])){
      $deseleccionartodos = "UPDATE `menciones` SET `seleccionado`='0'";
      $result = mysqli_query($db,$deseleccionartodos);
  }

    #Filtros de clasificación
    if(isset($_POST['filtrar'])){ 
      $filtro = $_POST['filtro']; 
    }

    function contadorUsuarios($filtro){
      ?>Nº usuarios <span class="badge badge-pill badge-light">
        <?php include "config.php";
        if ($filtro == 1) {
          $contador = "SELECT * FROM `menciones` where `count` > 1 and `eliminado` = '0' and `post`='0'";
        } else if ($filtro == 2) {
          $contador = "SELECT * FROM `menciones` where `countres` > 1 and `eliminado` = '0' and `post`='0'";
        } else if ($filtro == 3) {
          $contador = "SELECT * FROM `menciones` where `countsemana` > 1 and `eliminado` = '0' and `post`='0'";
        } else {
          $contador = "SELECT * FROM `menciones` where `countotal` > 1 and `eliminado` = '0' and `post`='0'";
        }
        
        if ($result = $db->query($contador)) {
          /* determinar el número de filas del resultado */
          $row_cnt = $result->num_rows;
          echo $row_cnt;  
        }                                                                             
        ?>
        </span> 
    <?php
    }

    #Funcion para eliminar TODOS
    function eliminarTodosUsuarios(){
      include "config.php";
      if(isset($_POST['eliminarTodos'])){
        $eliminarTodos = "DELETE FROM `menciones`";
        $result = mysqli_query($db,$eliminarTodos);
        ?>
        <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
          <span class="badge badge-pill badge-danger">Eliminados</span>
          Se elimino todos los usuarios con exito.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <?php
      }
    }

    #Funcion para eliminar un determinado Hashtag
    function eliminarUsuario($idUsuario){
        include "config.php";
        $eliminar = "UPDATE `menciones` SET `eliminado`='1' WHERE `id` = $idUsuario";
        $result = mysqli_query($db,$eliminar);
        ?>
        <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
            <span class="badge badge-pill badge-danger">Eliminado</span>
            Se elimino el hashtag con exito.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <?php
    }

    #Consulta de datos del filtro
    function consultarUsuarios($filtro){
      include "config.php";
      if ($filtro == 2){
        $query = "SELECT * FROM `menciones` where `eliminado` = '0' and `post`='0' order by count DESC LIMIT 100";
      }elseif ($filtro == 3){
        $query = "SELECT * FROM `menciones` where `eliminado` = '0' and `post`='0' order by countsemana DESC LIMIT 100";

      }elseif ($filtro == 0){
        $query = "SELECT * FROM `menciones` where `eliminado` = '0' and `post`='0' order by countotal DESC LIMIT 100";

      } else {
        $query = "SELECT * FROM `menciones` where `eliminado` = '0' and `post`='0' order by count DESC LIMIT 100";
      }         
      return mysqli_query($db,$query);
    }
                                          

    
   ?>
