<?php

/** 
 *  Funciones para los usuarios
 * 
 * @package  UAL Transfiere
 * @author   Alberto Fuentes <aff012@inlumine.ual.es>
 * @link     https://twitter.com/21albertoff
 *
 */

   $filtro = 0;

  #Filtro para ver posteadoresd eun hashtags
   if(isset($_POST['verposteadores'])){
    $IdH= $_POST['idHashtag'];
    $query = "SELECT * FROM `hashtags` where `id`=".$IdH."";
    $result = mysqli_query($db,$query);
    if($result){
       while($row = mysqli_fetch_array($result)){
          $nombreH = $row['hashtag'];
       }
    }
  } 
    #Filtro para seleccionar
    if(isset($_POST['seleccionar'])){
       $idUsuario = $_POST['idUsuario'];
       $seleccionar = "UPDATE `usuarios` SET `seleccionado`='1' WHERE `id` = $idUsuario";
       $result = mysqli_query($db,$seleccionar);
   }

   #Filtro para agregar nueva reglla
   if(isset($_POST['nuevaregla'])){
      // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
      $ch = curl_init();
      $nombreUsuario = $_POST['nombreUsuario'];
      $idUsuario = $_POST['idUsuario'];
      $regla = "{ \"add\": [ {\"value\": \"from:".$nombreUsuario."\", \"tag\": \"".$nombreUsuario." user\"}] }";

      curl_setopt($ch, CURLOPT_URL, 'https://api.twitter.com/2/tweets/search/stream/rules');
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_POST, 1);
      curl_setopt($ch, CURLOPT_POSTFIELDS, $regla);

      $headers = array();
      $headers[] = 'Content-Type: application/json';
      $headers[] = 'Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAPbENwEAAAAAo90kIhuPyTepkpQ5IN5OrhtlOtA%3DYedpthaxickJlKMh1LiZK3zGGMsCKfmbAnsoVnaBCc3yLSt9f4';
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

      $result = curl_exec($ch);
      if (curl_errno($ch)) {
         echo 'Error:' . curl_error($ch);
      }
      curl_close($ch);
      $post = "UPDATE `usuarios` SET `post`=1 WHERE `id` = $idUsuario";
      $result = mysqli_query($db,$post);
   }
   
   #Filtro para deseleccionar
   if(isset($_POST['deseleccionar'])){
       $idUsuario = $_POST['idUsuario'];
       $deseleccionar = "UPDATE `usuarios` SET `seleccionado`='0' WHERE `id` = $idUsuario";
       $result = mysqli_query($db,$deseleccionar);
   }

    #Filtro para recopilar datos
    if(isset($_POST['recopilar'])){
        $recopilar = "UPDATE `usuarios` SET `tweetssemana`=`tweetstres`";
        $result = mysqli_query($db,$recopilar);
        $recopilar2 = "UPDATE `usuarios` SET `tweetstres`=`count`";
        $result = mysqli_query($db,$recopilar2);
        $recopilar3 = "UPDATE `usuarios` SET `tweets`=1";
        $result = mysqli_query($db,$recopilar3);
    }

    #Filtro para recopilar datos
    if(isset($_POST['deseleccionarTodos'])){
      $deseleccionartodos = "UPDATE `usuarios` SET `seleccionado`='0'";
      $result = mysqli_query($db,$deseleccionartodos);
  }

    #Filtros de clasificación
    if(isset($_POST['filtrar'])){ 
      $filtro = $_POST['filtro']; 
    }

    function contadorUsuarios($filtro){
      ?>Nº usuarios <span class="badge badge-pill badge-light">
        <?php include "config.php";
        if ($filtro == 1) {
          $contador = "SELECT * FROM `usuarios` where `tweets` > 1 and `eliminado` = '0'";
        } else if ($filtro == 2) {
          $contador = "SELECT * FROM `usuarios` where `tweetstres` > 1 and `eliminado` = '0'";
        } else if ($filtro == 3) {
          $contador = "SELECT * FROM `usuarios` where `tweetssemana` > 1 and `eliminado` = '0'";
        } else {
          $contador = "SELECT * FROM `usuarios` where `tweetstotal` > 1 and `eliminado` = '0'";
        }
        
        if ($result = $db->query($contador)) {
          /* determinar el número de filas del resultado */
          $row_cnt = $result->num_rows;
          echo $row_cnt;  
        }                                                                             
        ?>
        </span> 
    <?php
    }

    #Funcion para eliminar TODOS
    function eliminarTodosUsuarios(){
      include "config.php";
      if(isset($_POST['eliminarTodos'])){
        $eliminarTodos = "DELETE FROM `usuarios`";
        $result = mysqli_query($db,$eliminarTodos);
        ?>
        <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
          <span class="badge badge-pill badge-danger">Eliminados</span>
          Se elimino todos los usuarios con exito.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <?php
      }
    }

    #Funcion para eliminar un determinado Hashtag
    function eliminarUsuario($idUsuario){
        include "config.php";
        $eliminar = "UPDATE `usuarios` SET `eliminado`='1' WHERE `id` = $idUsuario";
        $result = mysqli_query($db,$eliminar);
        ?>
        <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
            <span class="badge badge-pill badge-danger">Eliminado</span>
            Se elimino el hashtag con exito.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <?php
    }

    #Consulta de datos del filtro
    function consultarUsuarios($filtro){
      include "config.php";
      if ($filtro == 2){
        $query = "SELECT *, ((tweetstres*followers)/1000000) as `influencia` FROM `usuarios` where `eliminado` = '0' and `post`='0'ORDER BY `influencia` DESC LIMIT 50";
      }elseif ($filtro == 3){
        $query = "SELECT *, ((tweetssemana*followers)/1000000) as `influencia` FROM `usuarios` where `eliminado` = '0' and `post`='0'ORDER BY `influencia` DESC LIMIT 50";

      }elseif ($filtro == 0){
        $query = "SELECT *, ((tweetstotal*followers)/1000000) as `influencia` FROM `usuarios` where `eliminado` = '0' and `post`='0'ORDER BY `influencia` DESC LIMIT 50";

      } else {
        $query = "SELECT *, ((tweets*followers)/1000000) as `influencia` FROM `usuarios` where `eliminado` = '0' and `post`='0'ORDER BY `influencia` DESC LIMIT 50";
      }         
      return mysqli_query($db,$query);
    }

    function checkUsuariosSeleccionados(){
      include "config.php";
      $seleccionados = "SELECT COUNT(*) as cantidad FROM `usuarios` WHERE seleccionado = 1";
      $result = mysqli_query($db,$seleccionados);
      if($result){
          while($row = mysqli_fetch_array($result)){
            $cantidadSeleccionados = $row['cantidad'];
          }
      }
      return $cantidadSeleccionados;
    }
    
    function resumenComparacionUsuarios(){
      include "config.php";
      $clasificacion = "SELECT * FROM `usuarios` WHERE `eliminado` = 0 and `seleccionado` = 1 and `tweetstotal` > 1 order by tweetstotal DESC LIMIT 2";
      $result = mysqli_query($db,$clasificacion);
      if($result){
          while($row = mysqli_fetch_array($result)){
              $cantidad = $row['tweets'];
              $cantidadtres = $row['tweetstres'];
              $cantidadsemana = $row['tweetssemana'];
              echo"<tr><td>#".$row['nickname']."</td><td class='text-right'>";
              if ($cantidad < $cantidadtres){
                  echo"<i class='fas fa-arrow-down' style='color:#ff7272'</i>";
              } else {
                  echo"<i class='fas fa-arrow-up' style='color:#47ffc9'</i>";
              }

              if ($cantidad < $cantidadsemana){
                  echo"<i class='fas fa-arrow-down' style='color:#ff7272'</i></td></tr>";
              } else {
                  echo"<i class='fas fa-arrow-up' style='color:#47ffc9'</i></td></tr>";
              }                                          
          }
      }
    }

    #Consulta de datos del filtro
    function consultarPadreUsuario($idUsuario){
      include "config.php";
      $padre = "0";
      $sentenciaPadre = "SELECT h.hashtag as hashtag, ph.count as cantidad FROM ph INNER JOIN hashtags h on h.id = ph.idh where idp = ".$idUsuario." and h.post = 1 order by cantidad DESC LIMIT 1";
      $result = mysqli_query($db,$sentenciaPadre);
      if($result){
        while($row = mysqli_fetch_array($result)){
                $padre = $row['hashtag'];
        }
      }else{
        $padre = "0";
      }
      
      return $padre;
    }

    
   ?>
